name = "hono-app"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"
# DEBUG = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MOCK_BUCKET"
# bucket_name = "mock-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"